### ISSUE TITLE
0019、App-H5 开发浏览器兼容性问题

### ISSUE THREAD

**Issue by yeshuai0329** [yeshuai0329/front-notes#19]
# App-H5 开发浏览器兼容性问题

### 001、ios Safari浏览器点击300ms延迟 ？

解决方法：

在html文件中添加以下代码

```html
    <meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover" />

// width=device-width
```

### 002、ios 全面屏高度百分百情况下会有安全区域，高度100vh会被浏览器遮挡？

解决方法：

在项目reset.css代码中添加一下代码

```css
/* // ios底部横条处理 */
@supports (bottom: env(safe-area-inset-bottom)) {
  .footer-ios {
    padding-bottom: env(safe-area-inset-bottom);
  }
}
```

在html中添加meta

```html
    <meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover" />

//  viewport-fit=cover
```

注意： 页面最外层不要写padding-bottom 会被覆盖

### 003、IOS移除橡皮筋功能

解决方法：

1. 下载`inobounce`的包

```bash
$ npm i inobounce -S
```

2. 在页面调用这个方法

```typescript
/**
 * 禁用ios橡皮筋
 */
React.useEffect(() => {
  const u = navigator.userAgent
  if (u.indexOf('iPhone') > -1) {
    inobounce.enable()
  }
  return () => {
    inobounce.disable()
  }
}, [])

```

3. 同时要在路由页面最外层加高度和样式 

```css
#root {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```
